runmode: debug                 # 开发模式, debug, release, test
addr: :8080                  # HTTP绑定端口
name: apiserver              # API Server的名字
url: http://127.0.0.1:8080   # pingServer函数请求的API服务器的ip:port
max_ping_count: 10           # pingServer函数try的次数

log:
  log_save_path: logs/
  log_save_name: log
  log_file_ext: log
  time_format: 20060102
  runtime_root_path: runtime/
